# Generated by Django 6.0.4 on 2026-04-29 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('general', 'General Feedback')], default='general', max_length=20)),
                ('message', models.TextField(help_text='The feedback message (max 2000 characters)', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feedback was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Whether an admin has reviewed this feedback')),
                ('user', models.ForeignKey(blank=True, help_text='The user who submitted this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mode', models.CharField(choices=[('quick', 'Quick Fix'), ('deep', 'Deep Rewrite')], default='quick', help_text='Which mode loads by default on the homepage', max_length=10)),
                ('default_tone', models.CharField(choices=[('default', 'Default'), ('casual', 'Casual'), ('formal', 'Formal'), ('academic', 'Academic'), ('simple', 'Simple'), ('summarize', 'Summarize'), ('expand', 'Expand')], default='default', help_text='Which tone is pre-selected in Deep Rewrite mode', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
