# Generated by Django 6.0.4 on 2026-04-30 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quick', 'Quick Fix'), ('deep', 'Deep Rewrite')], help_text='Quick Fix or Deep Rewrite', max_length=10)),
                ('tone', models.CharField(default='default', help_text='Which tone was selected', max_length=20)),
                ('language', models.CharField(default='English', help_text='Detected input language', max_length=50)),
                ('input_words', models.IntegerField(default=0, help_text='Word count of the original text')),
                ('output_words', models.IntegerField(default=0, help_text='Word count of the rewritten text')),
                ('input_chars', models.IntegerField(default=0, help_text='Character count of the original text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this rewrite happened')),
                ('user', models.ForeignKey(blank=True, help_text='The user who made this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewrite_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_rewrit_user_id_a8ff16_idx'), models.Index(fields=['-created_at'], name='core_rewrit_created_90ebd2_idx')],
            },
        ),
    ]
