# Generated by Django 6.0.4 on 2026-05-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
