# Generated by Django 6.0.4 on 2026-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpreferences_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User browser timezone (e.g., America/Denver)', max_length=63),
        ),
    ]
