# Generated by Django 6.0.4 on 2026-05-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpreferences_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Client IP address (for guest rate limiting)', null=True),
        ),
    ]
